                                                                        NUMPY LIBRARY                                                                                                       

'''<br>
@Author: Rahul <br>
@Date: 2024-08-13<br>
@Last Modified by: Rahul <br>
@Last Modified time: 2024-08-13<br>
@Title: Python program for Numpy build-In functions <br>
'''

In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.

In [2]:

def convert_numpy(num_list):

    '''
    Description: 
        The function converts a list of numeric values into a 1-dimensional NumPy array.
    Parameters:
        num_list (list): The list of numeric values to be converted.
    Return:
        numpy.ndarray: A 1-dimensional NumPy array containing the numeric values from the list.
    '''
    
    return np.array(num_list)
        
def main():

    num_list = [12.23, 13.32, 100, 36.32]
    numpy_num = convert_numpy(num_list)
    
    print(type(numpy_num))
    
if __name__ == "__main__":
    main()


<class 'numpy.ndarray'>


2.Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:

def create_matrix():
          
          '''
          Description: 
            The function to create and print 3x3 matrix 
          Parameters:
              none  
          Return :
              None
          '''
          
          matrix=np.array([[2,3,4],[5,6,7],[8,9,10]])

          print(matrix)
        
def main():
    
    create_matrix()
    
if __name__=="__main__":
    main()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
        
def main():
    
    vector = np.zeros(10)
    vector[5] = 11

    print(vector)
    
if __name__=="__main__":
    main()

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

In [5]:

def reverse_array(arr1):
    
    '''
    Description: 
        The function reverses the elements of a 1D NumPy array.
    Parameters:
        arr1 (numpy.ndarray): A 1D NumPy array to be reversed.
    Return:
        numpy.ndarray: A new 1D NumPy array with the elements in reverse order.
    '''
    
    return arr1[::-1]
        
def main():

    arr1 = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])
    result_arr = reverse_array(arr1)
    
    print(result_arr)
    
if __name__ == "__main__":
    main()


[36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [6]:

def to_zero(input_array):
    
    '''
    Description: 
        The function takes a 2D NumPy array filled with ones and modifies it so that all elements inside the border are set to zero, 
        leaving the border elements as ones.
    Parameters:
        input_array (numpy.ndarray): A 2D NumPy array where the border elements will remain as ones and the inner elements will be set to zero.
    Return:
        numpy.ndarray: The modified 2D NumPy array with ones on the border and zeros inside.
    '''
    
    input_array[1:-1, 1:-1] = 0
    return input_array
          
def main():
    input_array = np.array([[1., 1., 1., 1., 1.],
                            [1., 1., 1., 1., 1.],
                            [1., 1., 1., 1., 1.],
                            [1., 1., 1., 1., 1.],
                            [1., 1., 1., 1., 1.]])
    
    print("Original array: \n", input_array)
    print("Array after conversion: \n", to_zero(input_array))
    
if __name__ == "__main__":
    main()

Original array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array after conversion: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6.Write a Python program to add a border (filled with 0's) around an existing array.

In [7]:

def add_border(input_array1):

    '''
    Description: 
        The function adds a border of zeros around an existing NumPy array.
    Parameters:
        input_array1 (numpy.ndarray): The original 2D NumPy array to which the border will be added.
    Return:
        numpy.ndarray: A new NumPy array with a border of zeros added around the original array.
    '''
    
    result_arr = np.zeros((len(input_array1) + 2, len(input_array1[0]) + 2))
    result_arr[1:-1, 1:-1] = input_array1
    
    return result_arr

def main():

    input_array1 = np.array([[1, 1, 1],
                             [1, 1, 1],
                             [1, 1, 1]])
    
    print("Original Array\n", input_array1)
    
    result_arr = add_border(input_array1)
    print("Array with Border\n", result_arr)
    
if __name__ == "__main__":
    main()


Original Array
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Array with Border
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:

def check_board():

    '''
    Description: 
        The function creates an 8x8 matrix and fills it with a checkerboard pattern,
        where 1s and 0s alternate across the matrix.
    Parameters:
        None  
    Return:
        None
    '''
    
    checkBoard = np.zeros((8, 8), dtype=int)
    checkBoard[1::2, ::2] = 1  
    checkBoard[::2, 1::2] = 1
    
    print(checkBoard)
        
def main():
    check_board()
    
if __name__ == "__main__":
    main()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


9. Write a Python program to append values to the end of an array.

In [9]:

def append_array(num_arr, list_nums):

    '''
    Description: 
        The function appends values from a list to the end of a NumPy array and returns the resulting array.
    Parameters:
        num_arr (numpy.ndarray): The original NumPy array to which values will be appended.
        list_nums (list or numpy.ndarray): A list or array of numbers to append to the end of `num_arr`.
    Return:
        numpy.ndarray: A new NumPy array with the values from `list_nums` appended to `num_arr`.
    '''
    
    return np.append(num_arr, list_nums)
        
def main():
    
    num_arr = np.array([10, 20, 30])
    list_nums = [40, 50, 60]
    print(append_array(num_arr, list_nums))

if __name__ == "__main__":
    main()

[10 20 30 40 50 60]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [10]:

def find_real_and_imaginary(num_arr):

    '''
    Description: 
        The function takes an array of complex numbers and returns two arrays: 
        one containing the real parts and the other containing the imaginary parts of the input array.
    Parameters:
        num_arr (numpy.ndarray): The array of complex numbers.
    Return:
        tuple: A tuple containing:
            - real_arr (numpy.ndarray): An array of the real parts of the complex numbers.
            - img_arr (numpy.ndarray): An array of the imaginary parts of the complex numbers.
    '''
    
    real_arr = np.real(num_arr)
    img_arr = np.imag(num_arr)
    return real_arr, img_arr
        
def main():
    
    num_arr = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
    real_num, imag_num = find_real_and_imaginary(num_arr)

    print("Real parts:", real_num)
    print("Imaginary parts:", imag_num)
    
if __name__ == "__main__":
    main()

Real parts: [1.         0.70710678]
Imaginary parts: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [11]:

def find_size_in_bytes(num_arr):

    '''
    Description: 
        The function calculates the number of elements in a NumPy array, the size of one element in bytes, 
        and the total bytes consumed by all elements of the array.
    Parameters:
        num_arr (numpy.ndarray): The NumPy array for which the size information is to be computed.
    Return:
        tuple: A tuple containing:
            - size_of_array (int): The number of elements in the array.
            - length_of_array (int): The length of one array element in bytes.
            - total_bytes (int): The total bytes consumed by the elements of the array.
    '''
    
    size_of_array = num_arr.size
    length_of_array = num_arr.itemsize
    total_bytes = num_arr.nbytes
    return size_of_array, length_of_array, total_bytes
        
def main():
    
    num_arr = np.array([1, 2, 3])
    size_of_array, length_of_array, total_bytes = find_size_in_bytes(num_arr)

    print("Size of the array:", size_of_array)
    print("Length of one array element in bytes:", length_of_array)
    print("Total bytes consumed by the elements of the array:", total_bytes)
    
    
if __name__ == "__main__":
    main()


Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.

In [12]:

def find_common(arr1, arr2):

    '''
    Description: 
        The function finds the common values between two NumPy arrays. 
        It returns the sorted, unique values that are present in both `arr1` and `arr2`.
    Parameters:
        arr1 (numpy.ndarray): The first NumPy array for comparison.
        arr2 (numpy.ndarray): The second NumPy array for comparison.
    Return:
        numpy.ndarray: An array containing the sorted, unique values that are common to both `arr1` and `arr2`.
    '''
    
    return np.intersect1d(arr1, arr2)
        
def main():

    arr1 = np.array([10, 20, 30])
    arr2 = np.array([10, 40, 50])
    common_items = find_common(arr1, arr2)
    
    print(common_items)

if __name__ == "__main__":
    main()

[10]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [13]:

def find_difference(arr1, arr2):

    '''
    Description: 
        The function finds the set difference between two NumPy arrays. 
        It returns the sorted, unique values in `arr1` that are not present in `arr2`.
    Parameters:
        arr1 (numpy.ndarray): The first NumPy array from which elements are selected.
        arr2 (numpy.ndarray): The second NumPy array used to exclude elements from `arr1`.
    Return:
        numpy.ndarray: An array containing the sorted, unique values that are in `arr1` but not in `arr2`.
    '''
    
    return np.setdiff1d(arr1, arr2)
        
        
def main():

    arr1 = np.array([10, 20, 30])
    arr2 = np.array([10, 40, 50])
    
    print(find_difference(arr1, arr2))
    
if __name__ == "__main__":
    main()

[20 30]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [14]:

def set_or_difference(array1, array2):

    '''
    Description: 
        The function finds the set exclusive-or (symmetric difference) of two NumPy arrays. 
        It returns the sorted, unique values that are in only one of the input arrays, but not in both.
    Parameters:
        array1 (numpy.ndarray): The first NumPy array for comparison.
        array2 (numpy.ndarray): The second NumPy array for comparison.
    Return:
        numpy.ndarray: An array containing the sorted, unique values that are in only one of the input arrays.
    '''
    
    return np.setxor1d(array1, array2)
        
def main():

    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70])
    
    print(set_or_difference(array1, array2))
    
if __name__ == "__main__":
    main()

[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [15]:

def compare_Two_arrays(array1, array2):

    '''
    Description: 
        The function compares two NumPy arrays element-wise and prints the results of 
        various comparison operations (greater than, greater than or equal to, less than, and equal to).
    Parameters:
        array1 (numpy.ndarray): The first NumPy array for comparison.
        array2 (numpy.ndarray): The second NumPy array for comparison.
    Return:
        None
    '''
    
    print("Greater than :",array1 > array2)
    print("Greater than or equal :",array1 >= array2)
    print("Lesser than :",array1 < array2)
    print("equals :",array1 == array2)

def main():

    array1 = np.array([1, 2, 3, 4, 5])
    array2 = np.array([1, 2, 0, 4, 0])
    
    compare_Two_arrays(array1, array2)
    
if __name__ == "__main__":
    main()

Greater than : [False False  True False  True]
Greater than or equal : [ True  True  True  True  True]
Lesser than : [False False False False False]
equals : [ True  True False  True False]


16. Write a Python program to save a NumPy array to a text file.

In [29]:

def write_in_file(num_array):

    '''
    Description: 
        The function saves a given NumPy array to a text file and then reads the file to display its content.
    Parameters:
        num_array (numpy.ndarray): The NumPy array to be saved to the file.
    Return:
        None
    '''

    # file_path = "C:/Users/rahul/Desktop/Python Libraries/ArrayList.txt"
    
    # Write to the file
    # with open(file_path, 'w') as file:
    #     file.write(str(num_array))
    
    # Read from the file and print the content
    # with open(file_path, 'r') as file:
    #     content = file.read()
    #     print(content)

    #Using savetxt in numpy
    np.savetxt("ArrayList.txt",num_array,fmt="%d") 
          
def main():

    num_array = np.array([1, 2, 3, 4, 5])
    write_in_file(num_array)
    
if __name__=="__main__":
    main()

17. Write a Python program to create a contiguous flattened array.

In [17]:

def re_shape(array1):

    '''
    Description: 
        The function reshapes a given multi-dimensional Numpy array into a 
        1-dimensional contiguous flattened array.
    Parameters:
        array1 (numpy.ndarray): The multi-dimensional Numpy array to be flattened.
    Return:
        numpy.ndarray: A 1-dimensional flattened Numpy array.
    '''
    
    return array1.reshape(-1)

def main():
    
    array1 = np.array([[1, 2, 3, 4, 5], [1, 2, 0, 4, 0]])
    print(re_shape(array1))
    
if __name__=="__main__":
    main()

[1 2 3 4 5 1 2 0 4 0]


18. Write a Python program to change the data type of an array.

In [18]:

def convert_datatype(array1):

    '''
    Description: 
        The function converts the data type of the given Numpy array to a specified type.
    Parameters:
        array1 (numpy.ndarray): The Numpy array whose data type needs to be changed.
    Return:
        numpy.ndarray: A new Numpy array with the data type converted to string.
    '''
    
    return np.array(array1, dtype=str)

def main():

    array1 = np.array([1, 2, 3, 4, 5], dtype=float)
    
    print("Before Converting:", array1)
    print("After Converting:", convert_datatype(array1))
    
if __name__=="__main__":
    main()

Before Converting: [1. 2. 3. 4. 5.]
After Converting: ['1.0' '2.0' '3.0' '4.0' '5.0']


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [19]:

def create_digonal():

    '''
    Description: 
        The function creates a 2-dimensional Numpy array (matrix) of shape (3, 3) 
        with ones on the diagonal and zeros elsewhere.
    Parameters:
        None
    Return:
        numpy.ndarray: A 2D Numpy array with ones on the diagonal and zeros elsewhere.
    '''
    
    matrix = np.zeros((3,3), dtype=int)
    for i in range(0,3):
        matrix[i, i] = 1
    return matrix

def main():
    
    print(create_digonal())
    
if __name__=="__main__":
    main()


[[1 0 0]
 [0 1 0]
 [0 0 1]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [20]:

def create_diagonal():
    
    '''
    Description: 
        Creates a 4x3 NumPy array with a specific pattern where each row i contains i ones at the beginning.
    Parameters:
        None
    Return:
        None
    '''
    matrix = np.zeros((4, 3), dtype=int)
    for i in range(1, 4):
        for j in range(i):
            matrix[i, j] = 1
    print(matrix)

def main():
    create_diagonal()
    
if __name__ == "__main__":
    main()


[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


21. Write a Python program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])

In [21]:

def merge_array(sample_array):

    '''
    Description: 
        Concatenates two 2-dimensional arrays along their common axis, transposes the resulting array,
        and reshapes it for output.
    Parameters:
        sample_array (numpy.ndarray): A 3-dimensional NumPy array where each 2-dimensional sub-array
                                      represents the arrays to be concatenated.
    Return:
        None
    '''
    output_array = sample_array.transpose(1, 0, 2)
    output_array = output_array.reshape(2, -1)

    print(output_array)      

def main():

    sample_arrays = np.array([[[0, 1, 3], [5, 7, 9]], 
                              [[0, 2, 4], [6, 8, 10]]])
    
    merge_array(sample_arrays)
    
if __name__ == "__main__":
    main()

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only).

In [22]:

def make_immutable(input_array):

    '''
    Description: 
        Makes a NumPy array immutable (read-only) by setting its writeable flag to False.
    Parameters:
        input_array (numpy.ndarray): The NumPy array to be made immutable.
    Return:
        numpy.ndarray: The same NumPy array with its writeable flag set to False.
    '''

    input_array.flags.writeable = False   
    return input_array

def main():

    input_array = np.array([1, 2, 3, 4])
    immutable_array = make_immutable(input_array)

    try:
        immutable_array[0] = 10
        
    except ValueError as e:  # Changed to ValueError as this is the correct exception
        print("The input_array is in Read-Only mode")

if __name__ == "__main__":
    main()

The input_array is in Read-Only mode


23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [23]:

def create_array():

    '''
    Description: 
        Creates a NumPy array of shape (3, 4), fills it with sequential values, multiplies each element by 3, and prints the resulting array.
    Parameters:
        None
    Return:
        None
    '''

    count = 0
    multiple_Of_Three = np.ones([3, 4], dtype=int)

    for i in range(3):  
        for j in range(4):   
            multiple_Of_Three[i, j] = count
            count += 1

    multiple_Of_Three *= 3  
    
    print(multiple_Of_Three)

def main():
    create_array()
    
if __name__ == "__main__":
    main()


[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Python program to convert a NumPy array into Python list structure.

In [24]:

def to_list(arr1):

    '''
    Description: 
        Converts a 2-dimensional NumPy array into a Python list of lists.
    Parameters:
        arr1 (numpy.ndarray): A 2-dimensional NumPy array.
    Return:
        List[List]: A list of lists where each sub-list corresponds to a row in the original NumPy array.
    '''

    num_list = []

    for row in arr1:
        num_list.append(row.tolist())  # Converting each row to a list
    
    return num_list

def main():
    
    arr1 = np.array([[0, 1],
                     [2, 3],
                     [4, 5]])
    
    print(to_list(arr1))  # This will print <class 'list'>
    
if __name__ == "__main__":
    main()


[[0, 1], [2, 3], [4, 5]]


25. Write a Python program to convert a NumPy array into Python list structure.

In [25]:

def to_list(arr1):
    
    '''
    Description: 
        Converts a 1-dimensional NumPy array into a Python list with each element rounded to 3 decimal places.
    Parameters:
        arr1 (numpy.ndarray): A 1-dimensional NumPy array.
    Return:
        List[float]: A list of floats where each element is rounded to 3 decimal places.
    '''
    num_list = []
    for element in arr1:
        num_list.append(float(round(element, 3)))
    
    return num_list

def main():
    arr1 = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 
                     0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
    print(to_list(arr1))
    
if __name__ == "__main__":
    main()

[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [26]:

def suppresses_array(arr1):
    '''
    Description: 
        Suppresses the use of scientific notation for small numbers in a NumPy array and sets the precision for printed output.
    Parameters:
        arr1 (numpy.ndarray): The NumPy array whose elements' scientific notation is to be suppressed.
    Return:
        numpy.ndarray: The original NumPy array with scientific notation suppressed for printing.
    '''
    np.set_printoptions(suppress=True, precision=3)
    return arr1

def main():
    arr1 = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
    arr = suppresses_array(arr1)
    print("[", " ".join(format(x, ".3f") for x in arr), "]")
    
if __name__ == "__main__":
    main()

[ 0.000 1.600 1200.000 0.235 ]


27. Write a Python program to how to add an extra column to an numpy array.

In [27]:

def add_column(arr1, new_column):
    '''
    Description: 
        Adds a new column to a 2-dimensional NumPy array.
    Parameters:
        arr1 (numpy.ndarray): The original 2-dimensional NumPy array.
        new_column (numpy.ndarray): The new column to be added as a 2-dimensional array.
    Return:
        numpy.ndarray: A new NumPy array with the extra column added.
    '''
    return np.column_stack((arr1, new_column))

def main():
    arr1 = np.array([[10, 20, 30],
                     [40, 50, 60]])
    new_column = np.array([[100], [200]])
    print(add_column(arr1, new_column))
    
if __name__ == "__main__":
    main()

[[ 10  20  30 100]
 [ 40  50  60 200]]


28. Write a Python program to remove specific elements in a numpy array.

In [28]:

def remove_element(arr1, positions):
    '''
    Description: 
        Removes specific elements from a 1-dimensional NumPy array based on given indices.
    Parameters:
        arr1 (numpy.ndarray): The original 1-dimensional NumPy array.
        positions (List[int]): A list of indices corresponding to the elements to be removed.
    Return:
        numpy.ndarray: A new NumPy array with the specified elements removed.
    '''
    return np.delete(arr1, positions)

def main():
    arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    indices_to_delete = [0, 3, 4]
    print(remove_element(arr1, indices_to_delete))

if __name__ == "__main__":
    main()

[ 20  30  60  70  80  90 100]
